"""add_ai_fields_to_tasks

Revision ID: 5000f09530ba
Revises: 44f5659abff5
Create Date: 2025-11-30 02:21:22.843495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5000f09530ba'
down_revision: Union[str, Sequence[str], None] = '44f5659abff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('complexity_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'complexity_score')
    op.drop_column('tasks', 'estimated_hours')
    # ### end Alembic commands ###
